### ISSUE TITLE
Asynchronously query explores

### ISSUE THREAD

**Issue by joshtemple** [dbanalyticsco/Fonz#20]
To speed up Fonz, we should consider using the `Run Query Async` endpoint and parallelizing our requests to run each explore. We can essentially launch each query required, then check on the status of each until a result is obtained. We should probably be able to set a limit on the number of parallel queries in case a database has low concurrency limits.

I'm guessing the `asyncio` library also has some useful tools for this.

If we get enough of a speed up, we can consider a toggled mode (or perhaps even default behavior) to do one query per dimension. This improves the UX because you can see all existing errors at once, rather than one error per explore.

**Comment by joshtemple** [comment]
Another advantage of this 1:1 query to dimension setup is we gain knowledge of exactly which dimension is triggering the error. Currently we can't determine which dimension in the query is triggering an error.

This would allow us to display the `lookml_link` field of the dimension returned by the LookML API endpoint for errored fields so the user can click through directly to the LookML definition.

This would be really slick and make local testing faster and smoother.

**Comment by joshtemple** [comment]
It looks like the response [headers contain information about rate limits](https://github.com/looker/looker-sdk-ruby/blob/master/lib/looker-sdk/rate_limit.rb), though it isn't documented as far as I can tell. It will be important to build this in a way that respects 429 responses and monitors the number of remaining requests so we don't max out the rate limit.

**Comment by joshtemple** [comment]
@DylanBaker, I did some testing with this in an async setup and it takes 28 seconds to loop through an explore with 100 dimensions on my warehouse. I think **0.28 s/dimension** is pretty fast, but it could still add up quickly for big projects and big tables (I used a tiny seed table to test this).

I think this is a viable setup, but probably should be enabled by a flag and not by default, otherwise it will be too time-consuming for CI.

I also talked with Looker support about rate limits. Looker doesn't really impose rate limits on their APIs, unless it's a self-hosted instance with some kind of load balancer sitting in front of it. For Looker-hosted, they recommend you keep parallelism for your whole instance down to 200 and below. Since this is an asynchronous and not multithreaded approach, it executes on a single thread (as far as I can tell), so the concurrency should never reach that high. The `aiohttp` library has a cap at 100 simultaneous connections anyway, so this shouldn't be an issue.

I'll flesh out my test approach some more and push up a PR so we can review together. I'm not an async expert, so it might be worth having a software engineer look over the code for a sanity check.

**Comment by joshtemple** [comment]
@DylanBaker, apologies for all the comments but thought we should align on UX before I go any farther with this.

Here's my proposal, would love to get your thoughts.

We provide a flag to `fonz sql` called `--batch` which is _disabled_ by default.

In the default state, we execute one query per dimension. This allows us to return LookML links on error and see _all_ the broken dimensions with a single query. The tradeoff is a longer execution time and a more expensive use of the Looker API (adds some slight risk in my mind).

When `batch` is enabled, we run the queries with all dimensions by explore. Here we won't be able to provide LookML links on error or test for multiple errors in an explore. We'll get a maximum of one error per explore with this approach.

**Comment by DylanBaker** [comment]
Hey. This all makes sense. Wanted to clarify something. You've said both:
> I think this is a viable setup, but probably should be enabled by a flag and not by default, otherwise it will be too time-consuming for CI.

> In the default state, we execute one query per dimension. 

The latter statement is from your more recent comment, so I imagine that's the one you would now prefer?

With respect to CLI syntax, I'm happy with `--batch` (on the assumption the default is disabled). If we go the other route, I think we there's a better term to reflect running everything separately.
