### ISSUE TITLE
Hidden ARRAY and STRUCT columns

### ISSUE THREAD

**Issue by joshtemple** [dbanalyticsco/Fonz#35]
There's a common pattern in BigQuery to represent a nested field (`STRUCT` or `ARRAY` type) as a dimension and a view that is joined with an `UNNEST` statement.

Currently, Fonz errors when testing these dimensions because you can't group by a nested field. These are hidden dimensions because you can't actually query them, but you need them for sole purpose of joining the nested field view to the full table.

([Here's the approach for reference](https://discourse.looker.com/t/modeling-nested-data-in-big-query-standard-sql/3866))

This raises the **larger question**, should we skip `hidden: yes` fields by default since they can't actually be queried? My inclination is yes.

**Comment by joshtemple** [comment]
After thinking about this some more, maybe we should stick to having our own syntax to ignore a dimension as previously discussed.

It's also a common pattern to hide a numeric dimension that's used primarily to generate a measure (like a revenue dimension, for instance), and this would exclude those very important dimensions from testing.

**Comment by DylanBaker** [comment]
Yeah, I think the right way to handle this is to give them the option to ignore certain columns. I don't think we want to be too heavy-handed in our assumptions about what a hidden column means. As you said, they often get used in measures, etc.
